name: Deploy to Nexus Repository

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v3
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - name: Set env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

      # Import GPG keys
      - name: Import GPG key
        run: |
          echo "${{ secrets.GPG_PRIVATE_KEY }}" | gpg --import --batch --yes
          echo "${{ secrets.GPG_PUBLIC_KEY }}" | gpg --import --batch --yes
          echo -e "1234567890ABCDEF1234567890ABCDEF12345678:6:" | gpg --import-ownertrust

      # Configure GPG for Maven
      - name: Configure GPG for Maven
        run: |
          mkdir -p ~/.gnupg
          echo "allow-loopback-pinentry" >> ~/.gnupg/gpg-agent.conf
          echo "use-agent" >> ~/.gnupg/gpg.conf
          gpgconf --kill gpg-agent
          gpgconf --launch gpg-agent

      - name: Build with Maven
        run: mvn clean install -DskipTests

      - name: Nexus Repo Publish
        uses: sonatype-nexus-community/nexus-repo-github-action@master
        with:
          serverUrl: https://nexus.golden-developer.de
          username: github
          password: ${{ secrets.NEXUS_PASSWORD }}
          format: maven2
          repository: maven-releases
          coordinates: groupId=de.goldendeveloper artifactId=GithubAPI version=${{ env.RELEASE_VERSION }}
          assets: extension=jar
          filename: ./target/githubapi-${{ env.RELEASE_VERSION }}.jar
